In [124]:
# imports
import pandas as pd
from datetime import datetime
import re

In [126]:
# read the data (2012)
df = pd.read_csv('data/BPI_Challenge_2012-training.csv')

df_test = pd.read_csv('data/BPI_Challenge_2012-test.csv')

# read the data (road traffic fines)
# df = pd.read_csv('data/Road_Traffic_Fine_Management_Process-training.csv')

# read the data (2017)
# df = pd.read_csv('data/BPI Challenge 2017-training.csv')

# read the data (2018)
# df = pd.read_csv('data/BPI Challenge 2018-training.csv')

df.head(10)

,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp
0,0,173688,2011-10-01T00:38:44.546+02:00,20000,A_SUBMITTED,COMPLETE,01-10-2011 00:38:44.546
1,1,173688,2011-10-01T00:38:44.546+02:00,20000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 00:38:44.880
2,2,173688,2011-10-01T00:38:44.546+02:00,20000,A_PREACCEPTED,COMPLETE,01-10-2011 00:39:37.906
3,3,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,SCHEDULE,01-10-2011 00:39:38.875
4,4294967296,173691,2011-10-01T08:08:58.256+02:00,5000,A_SUBMITTED,COMPLETE,01-10-2011 08:08:58.256
5,4294967297,173691,2011-10-01T08:08:58.256+02:00,5000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 08:09:02.195
6,4294967298,173691,2011-10-01T08:08:58.256+02:00,5000,A_PREACCEPTED,COMPLETE,01-10-2011 08:09:56.648
7,4294967299,173691,2011-10-01T08:08:58.256+02:00,5000,W_Completeren aanvraag,SCHEDULE,01-10-2011 08:09:59.578
8,8589934592,173694,2011-10-01T08:10:30.287+02:00,7000,A_SUBMITTED,COMPLETE,01-10-2011 08:10:30.287
9,8589934593,173694,2011-10-01T08:10:30.287+02:00,7000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 08:10:30.591

In [127]:
# Defining database-specific variables
case_column = "case concept:name"
registration_time_column = "case REG_DATE"
event_column = "event concept:name"
timestamp_column = "event time:timestamp"
timeformat_registration = "%Y-%m-%dT%H:%M:%S" # new time format
timeformat_timestamp = "%d-%m-%Y %H:%M:%S.%f"

# Names of columns we will add in this notebook
position_column = "Position"
baseline_next_event_column = "Baseline Prediction for Next Activity"
# position_next_event_column = "Position Prediction for Next Activity"
# pos_event_next_event_column = "Position&Event Prediction for Next Activity"
baseline_next_timestamp_column = "Baseline Prediction for Next Timestamp"
# position_next_timestamp_column = "Position Prediction for Next Timestamp"
# pos_event_next_timestamp_column = "Position&Event Prediction for Next Timestamp"
# time_since_registration_column = "Time Since Registration"
# day_of_week_column = "day_of_week"
# month_of_year_column = "month_of_year"
# offer_sent = 'O_SENT' # the name a of a sent offer state within event_column

In [128]:
df[registration_time_column]= [re.sub('\..*|\+.*','',a,flags=re.DOTALL) for a in df[registration_time_column]]
df[registration_time_column] = [datetime.strptime(date, timeformat_registration) for date in df[registration_time_column]]
df[timestamp_column] = [datetime.strptime(date, timeformat_timestamp) for date in df[timestamp_column]]
df = df.sort_values(by=[case_column, timestamp_column]).reset_index() # sort values by user and time of event
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214377 entries, 0 to 214376
Data columns (total 8 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   index                       214377 non-null  int64
 1   eventID                     214377 non-null  int64
 2   case concept:name           214377 non-null  int64
 3   case REG_DATE               214377 non-null  datetime64[ns]
 4   case AMOUNT_REQ             214377 non-null  int64
 5   event concept:name          214377 non-null  object
 6   event lifecycle:transition  214377 non-null  object
 7   event time:timestamp        214377 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(4), object(2)
memory usage: 13.1+ MB

In [129]:
df_test[registration_time_column]= [re.sub('\..*|\+.*','',a,flags=re.DOTALL) for a in df_test[registration_time_column]]
df_test[registration_time_column] = [datetime.strptime(date, timeformat_registration) for date in df_test[registration_time_column]]
df_test[timestamp_column] = [datetime.strptime(date, timeformat_timestamp) for date in df_test[timestamp_column]]
df_test = df_test.sort_values(by=[case_column, timestamp_column]).reset_index() # sort values by user and time of event
#df_test.info()

In [130]:
# adding the day of the week and month of the year columns

# df[time_since_registration_column] = df[timestamp_column] - df[registration_time_column] # Adding time since registration 
# df[day_of_week_column] = df[timestamp_column].dt.day_name()
# df[month_of_year_column] = df[timestamp_column].dt.month_name()

In [131]:
# add column offer sent (binary)
# df_offersentevents = df[df[event_column] == offer_sent]
# df_firsteventofcase = df_offersentevents[df_offersentevents[case_column].shift(periods=1) != df_offersentevents[case_column]]
# dict_timestamp_offer_sent = dict(zip(df_firsteventofcase[case_column],df_firsteventofcase[timestamp_column]))

# df[offer_sent] = [(True if ((case in dict_timestamp_offer_sent) and (dict_timestamp_offer_sent[case] <= time)) else False) for case,time in zip(df[case_column],df[timestamp_column])]
#df.head(40)

In [132]:
# We create a dictionary length_process that stores the total length of a trace indexed by the case number
# We fill in the Position column that shows which position is a certain event in the trace (the first event is 1)

df[position_column] = df.groupby([case_column]).cumcount()+1
#length_process = df.groupby([case_column]).size().to_dict()

#length_process
#df[df[case_column] == 173688]

In [133]:
# here you can see different statistics about the process length
# print(f'Mean: {statistics.mean(length_process.values())}')
#print(f'Mode: {statistics.mode(length_process.values())}') # This line can cause a critical error if there exist multiple modes
# print(f'Median: {statistics.median(length_process.values())}')
# print(f'Max: {max(length_process.values())}') # this is df[df['case concept:name'] == 185548]
# print(f'Min: {min(length_process.values())}')

In [134]:
# the dictionary prediction_step stores the most common event for each position (if there are multiple modes we pick the first event that is encountered)
# for example, the most common activity to occur in position 2 is prediction_step[1]; prediction for position n+1 is prediction_step[n]
# If there is no next prediction after position n then prediction_step[n] == "-"

# prediction_step = {i: df[event_column][df[position_column] == i+1].mode()[0] for i in range(1, max(length_process.values()))}
# prediction_step[max(length_process.values())] = "-"

#prediction_step

In [135]:
# We add the predicted next event (based on position only) as a new column to the dataframe
#df[position_next_event_column] = [prediction_step[x] for x in df[position_column]]

#df[df[case_column] == 173688]

In [136]:
# We create a dictionary to store the average time duration until the next event
# For example the average time duration between position n and n+1 is average_time_per_pos[n]
# The dataframe must be sorted on case-number and timestamp for this calculation to work!
# if there exists no event in the dataset of n+1 then average_time_per_pos[n] == pd.Timedelta(0)

# Code Explanation: We subtract the timestamps and then shift the results up so the difference from n to n+1 is on row n.
# Only if both events are in the same trace should include the row in the mean() calculation.
shifted_deltatimes = df[timestamp_column].diff().shift(periods=-1)[df[case_column].shift(periods=-1) == df[case_column]]

# The mean() function will return NaT if the input is empty, we replace this with pd.Timedelta(0)
def replacenat(timedelt):
    if (pd.isna(timedelt)):
        return pd.Timedelta(0)
    return timedelt

# We select only the rows of a certain position i and then calculate the mean() on those timedeltas

# average_time_per_pos = {i: replacenat(shifted_deltatimes[df[position_column] == i].mean()) for i in range(1, max(length_process.values()) + 1)}

#average_time_per_pos

In [137]:
df.head(30)

,index,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,Position
0,0,0,173688,2011-10-01 00:38:44,20000,A_SUBMITTED,COMPLETE,2011-10-01 00:38:44.546,1
1,1,1,173688,2011-10-01 00:38:44,20000,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 00:38:44.880,2
2,2,2,173688,2011-10-01 00:38:44,20000,A_PREACCEPTED,COMPLETE,2011-10-01 00:39:37.906,3
3,3,3,173688,2011-10-01 00:38:44,20000,W_Completeren aanvraag,SCHEDULE,2011-10-01 00:39:38.875,4
4,89,4,173688,2011-10-01 00:38:44,20000,W_Completeren aanvraag,START,2011-10-01 11:36:46.437,5
5,94,5,173688,2011-10-01 00:38:44,20000,A_ACCEPTED,COMPLETE,2011-10-01 11:42:43.308,6
6,98,7,173688,2011-10-01 00:38:44,20000,A_FINALIZED,COMPLETE,2011-10-01 11:45:09.243,7
7,99,6,173688,2011-10-01 00:38:44,20000,O_SELECTED,COMPLETE,2011-10-01 11:45:09.243,8
8,100,8,173688,2011-10-01 00:38:44,20000,O_CREATED,COMPLETE,2011-10-01 11:45:11.197,9
9,101,9,173688,2011-10-01 00:38:44,20000,O_SENT,COMPLETE,2011-10-01 11:45:11.380,10
10,102,10,173688,2011-10-01 00:38:44,20000,W_Nabellen offertes,SCHEDULE,2011-10-01 11:45:11.554,11
11,103,11,173688,2011-10-01 00:38:44,20000,W_Completeren aanvraag,COMPLETE,2011-10-01 11:45:13.917,12
12,117,12,173688,2011-10-01 00:38:44,20000,W_Nabellen offertes,START,2011-10-01 12:15:41.290,13
13,118,13,173688,2011-10-01 00:38:44,20000,W_Nabellen offertes,COMPLETE,2011-10-01 12:17:08.924,14
14,7544,14,173688,2011-10-01 00:38:44,20000,W_Nabellen offertes,START,2011-10-08 16:26:57.720,15
15,7548,15,173688,2011-10-01 00:38:44,20000,W_Nabellen offertes,COMPLETE,2011-10-08 16:32:00.886,16
16,8237,16,173688,2011-10-01 00:38:44,20000,W_Nabellen offertes,START,2011-10-10 11:32:22.495,17
17,8238,17,173688,2011-10-01 00:38:44,20000,O_SENT_BACK,COMPLETE,2011-10-10 11:33:03.668,18
18,8239,18,173688,2011-10-01 00:38:44,20000,W_Valideren aanvraag,SCHEDULE,2011-10-10 11:33:04.560,19
19,8240,19,173688,2011-10-01 00:38:44,20000,W_Nabellen offertes,COMPLETE,2011-10-10 11:33:05.791,20
20,12358,20,173688,2011-10-01 00:38:44,20000,W_Valideren aanvraag,START,2011-10-13 10:05:26.925,21
21,12413,23,173688,2011-10-01 00:38:44,20000,O_ACCEPTED,COMPLETE,2011-10-13 10:37:29.226,22
22,12414,21,173688,2011-10-01 00:38:44,20000,A_REGISTERED,COMPLETE,2011-10-13 10:37:29.226,23
23,12415,22,173688,2011-10-01 00:38:44,20000,A_APPROVED,COMPLETE,2011-10-13 10:37:29.226,24
24,12416,24,173688,2011-10-01 00:38:44,20000,A_ACTIVATED,COMPLETE,2011-10-13 10:37:29.226,25
25,12417,25,173688,2011-10-01 00:38:44,20000,W_Valideren aanvraag,COMPLETE,2011-10-13 10:37:37.026,26
26,4,4294967296,173691,2011-10-01 08:08:58,5000,A_SUBMITTED,COMPLETE,2011-10-01 08:08:58.256,1
27,5,4294967297,173691,2011-10-01 08:08:58,5000,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 08:09:02.195,2
28,6,4294967298,173691,2011-10-01 08:08:58,5000,A_PREACCEPTED,COMPLETE,2011-10-01 08:09:56.648,3
29,7,4294967299,173691,2011-10-01 08:08:58,5000,W_Completeren aanvraag,SCHEDULE,2011-10-01 08:09:59.578,4

In [138]:
# We add the predicted time duration until next event to the dataframe 
# df[position_next_timestamp_column] = [x + average_time_per_pos[y] for x,y in zip(df[timestamp_column], df[position_column])]

# df[df[case_column] == 185548] # Note that the events of pos 173 and 174 happen at the exact same timestamp!

In [139]:
# list of unique events in the data
unique_events = df[event_column].unique()

# dictionary to store the most common (mode) event following the key event
dict_common_next_event = {event: df[(df[case_column].shift(periods=-1) == df[case_column]) & (df[event_column].shift(periods=1) == event)][event_column].mode()[0] for event in unique_events}

#dict_common_next_event

In [140]:
# test = pd.Series(["test1", "test1", "test2", "test2"])
# test.mode()[0]

In [141]:
# We apply the dictionary to the dataset to get the baseline event prediction
df[baseline_next_event_column] = [(dict_common_next_event[event] if (event in dict_common_next_event) else "-") for event in df[event_column]]

#df[df[case_column] == 185548]

In [142]:
# dictionary to store the average time for each event
dict_time_per_event = {event: replacenat(shifted_deltatimes[df[event_column] == event].mean()) for event in unique_events}

# dict_hours_per_event = {event: (dict_time_per_event[event].total_seconds()/(60*60)) for event in unique_events}

#dict_time_per_event

# plt.bar(hours_per_event.keys(), hours_per_event.values())
# plt.show()

In [143]:
# apply the average time to the dataframe to get the baseline time prediction
df[baseline_next_timestamp_column] = [(time + dict_time_per_event[event] if (event in dict_time_per_event) else time) for event,time in zip(df[event_column], df[timestamp_column])]

df[df[case_column] == 185548]

,index,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,Position,Baseline Prediction for Next Activity,Baseline Prediction for Next Timestamp
78435,64935,16333760626688,185548,2011-11-15 13:42:45,20000,A_SUBMITTED,COMPLETE,2011-11-15 13:42:45.593,1,A_PARTLYSUBMITTED,2011-11-15 13:42:46.175640462
78436,64936,16333760626689,185548,2011-11-15 13:42:45,20000,A_PARTLYSUBMITTED,COMPLETE,2011-11-15 13:42:45.889,2,W_Afhandelen leads,2011-11-15 13:43:20.991779539
78437,64938,16333760626690,185548,2011-11-15 13:42:45,20000,A_PREACCEPTED,COMPLETE,2011-11-15 13:43:31.963,3,W_Completeren aanvraag,2011-11-15 13:43:32.465771753
78438,64939,16333760626691,185548,2011-11-15 13:42:45,20000,W_Completeren aanvraag,SCHEDULE,2011-11-15 13:43:32.557,4,W_Completeren aanvraag,2011-11-16 07:02:01.714379243
78439,64989,16333760626692,185548,2011-11-15 13:42:45,20000,W_Completeren aanvraag,START,2011-11-15 13:59:33.696,5,W_Completeren aanvraag,2011-11-16 07:18:02.853379243
...,...,...,...,...,...,...,...,...,...,...,...
78605,165456,16333760626858,185548,2011-11-15 13:42:45,20000,W_Nabellen incomplete dossiers,COMPLETE,2012-01-17 10:54:42.893,171,W_Nabellen incomplete dossiers,2012-01-17 18:08:57.358645946
78606,165539,16333760626859,185548,2011-11-15 13:42:45,20000,W_Nabellen incomplete dossiers,START,2012-01-17 11:20:51.763,172,W_Nabellen incomplete dossiers,2012-01-17 18:35:06.228645946
78607,165555,16333760626861,185548,2011-11-15 13:42:45,20000,O_CANCELLED,COMPLETE,2012-01-17 11:25:56.714,173,O_SELECTED,2012-01-17 11:25:58.074857292
78608,165556,16333760626860,185548,2011-11-15 13:42:45,20000,A_CANCELLED,COMPLETE,2012-01-17 11:25:56.714,174,A_SUBMITTED,2012-01-17 11:28:58.061432222
78609,165557,16333760626862,185548,2011-11-15 13:42:45,20000,W_Nabellen incomplete dossiers,COMPLETE,2012-01-17 11:26:00.120,175,W_Nabellen incomplete dossiers,2012-01-17 18:40:14.585645946

In [144]:
def getNumberOfActiveEvents(timestamp):
    assert isinstance(timestamp, pd.Timestamp)
    df_previousevents = df[df[timestamp_column] <= timestamp]
    df_lastrowofcase = df_previousevents[(df_previousevents[position_column].diff()!=1).shift(periods=-1, fill_value=True)]
    return {event: len(df_lastrowofcase[df_lastrowofcase[event_column] == event]) for event in unique_events}

getNumberOfActiveEvents(pd.Timestamp("2012-01-17 11:20:51.763"))

{'A_SUBMITTED': 0,
 'A_PARTLYSUBMITTED': 0,
 'A_PREACCEPTED': 0,
 'W_Completeren aanvraag': 1545,
 'A_ACCEPTED': 0,
 'A_FINALIZED': 0,
 'O_SELECTED': 0,
 'O_CREATED': 0,
 'O_SENT': 0,
 'W_Nabellen offertes': 1067,
 'O_SENT_BACK': 0,
 'W_Valideren aanvraag': 1618,
 'O_ACCEPTED': 0,
 'A_REGISTERED': 0,
 'A_APPROVED': 0,
 'A_ACTIVATED': 1,
 'O_CANCELLED': 141,
 'W_Wijzigen contractgegevens': 2,
 'A_DECLINED': 2323,
 'A_CANCELLED': 359,
 'W_Afhandelen leads': 1622,
 'O_DECLINED': 0,
 'W_Nabellen incomplete dossiers': 249,
 'W_Beoordelen fraude': 44}

In [145]:
# We create a list containing all unique combinations of position numbers and events that exist in the data

# unique_pos_event = list({(pos,event) for event,pos in zip(df[event_column],df[position_column])})

# len(unique_pos_event)

In [146]:
# We create dictionary that takes into account the most recent event AND the position in the trace to give the most likely next event

# The mode() function can return an empty series if the input is empty, then we should output "-"
def get_first_mode(srs):
    if (len(srs)>0):
        return srs[0]
    return "-"

# pos_event_prediction = {(pos,event): get_first_mode(df[event_column][(df[event_column].shift() == event) & (df[position_column] == pos+1)].mode()) for pos,event in unique_pos_event}

#pos_event_prediction#[("A_PARTLYSUBMITTED", 2)]

In [147]:
# We add the predicted next event as a new column to the dataframe
# df[pos_event_next_event_column] = [pos_event_prediction[(pos, event)] for pos,event in zip(df[position_column], df[event_column])]
#df[df[case_column] == 185548]

In [148]:
# We calculate the average time-difference between the next event and the current time for every pair of position

# pos_event_timedelta = {(pos,event): replacenat(shifted_deltatimes[(df[position_column]==pos)&(df[event_column]==event)].mean()) for pos,event in unique_pos_event}

#pos_event_timedelta

In [149]:
# We add the predicted next timestamp as a new column to the dataframe
# df[pos_event_next_timestamp_column] = [time+pos_event_timedelta[(pos,event)] for pos,event,time in zip(df[position_column], df[event_column], df[timestamp_column])]
# df[df[case_column] == 185548]

In [150]:
# Applying the baseline predictions to the test dataset
df_test[baseline_next_event_column] = [(dict_common_next_event[event] if (event in dict_common_next_event) else "-") for event in df_test[event_column]]

df_test[baseline_next_timestamp_column] = [(time + dict_time_per_event[event] if (event in dict_time_per_event) else time) for event,time in zip(df_test[event_column], df_test[timestamp_column])]

In [151]:
# Accuracy % of event predictions:

training_event_accuracy = len(df[(df[baseline_next_event_column].shift(periods=1)==df[event_column]) & (df[case_column].shift(periods=1) == df[case_column])]) * 100 / len(df[df[case_column].shift(periods=1) == df[case_column]])

test_event_accuracy = len(df_test[(df_test[baseline_next_event_column].shift(periods=1)==df_test[event_column]) & (df_test[case_column].shift(periods=1) == df_test[case_column])]) * 100 / len(df_test[df_test[case_column].shift(periods=1) == df_test[case_column]])

training_event_accuracy, test_event_accuracy

(64.9130980638327, 64.06370976661874)

In [152]:
# Mean Absolute Error of time predictions:

training_time_MAE = abs(df[timestamp_column] - df[baseline_next_timestamp_column].shift(periods=1))[df[case_column].shift(periods=1) == df[case_column]].mean()

test_time_MAE = abs(df_test[timestamp_column] - df_test[baseline_next_timestamp_column].shift(periods=1))[df_test[case_column].shift(periods=1) == df_test[case_column]].mean()

training_time_MAE, test_time_MAE

(Timedelta('0 days 16:20:59.739888261'),
 Timedelta('0 days 14:43:13.416911984'))